[package]
name = "cdshealpix"
version = "0.1.0"
authors = ["F.-X. Pineau <francois-xavier.pineau@astro.unistra.fr>"]
edition = "2018"


[lib]
name = "cdshealpix"
path = "src/lib.rs"
test = true
doctest = true
bench = true
doc = true


[[bin]]
name = "hpx"
path = "src/bin.rs"

[dependencies]
# External dependencies
structopt = "0.2"        # CLI lib (based on clap)
#rand = "0.6"

[features]
nightly = []
#default = []

[profile.release]
lto = true
debug = false
#panic = 'abort'



