[package]
name = "cdshealpix"
version = "0.1.2"
authors = ["F.-X. Pineau <francois-xavier.pineau@astro.unistra.fr>"]
edition = "2018"
license = "MIT/Apache-2.0"
readme = "README.md"
categories = ["algorithms", "science"] 
repository = "https://github.com/cds-astro/cds-healpix-rust/"
description = """
Rust implementation of the HEALPix tesselation.
"""
exclude = [
    "makeDoc.bash"
    "resources/4doc",
]


[lib]
name = "cdshealpix"
path = "src/lib.rs"
test = true
doctest = true
bench = true
doc = true

[dependencies]
# External dependencies
#structopt = "0.2"        # CLI lib (based on clap)

[features]
# nightly = []

[profile.release]
lto = true
debug = false


