[package]
name = "healpix"
version = "0.1.4"
authors = ["F.-X. Pineau <francois-xavier.pineau@astro.unistra.fr>"]
edition = "2018"

[build-dependencies]
cdshealpix = "0.5.2"

[dependencies]
cdshealpix = "0.5.2"
wasm-bindgen = "0.2.64"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true

